import { Img } from "./Img";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { Button } from "./Button";
import { Input } from "./Input";
import { CheckBox } from "./CheckBox";
import { SelectBox } from "./SelectBox";
import { Radio } from "./Radio";
import { RadioGroup } from "./RadioGroup";
export { Img, Text, Heading, Button, Input, CheckBox, SelectBox, Radio, RadioGroup };
